name: ByteCart
main: com.github.catageek.ByteCart.ByteCart
version: 1.2.0
permissions:
    bytecart.*:
        description: give access to all blocks
        children:
            bytecart.BC7001: true
            bytecart.BC7002: true
            bytecart.BC7003: true
            bytecart.BC7010: true
            bytecart.BC7011: true
            bytecart.BC7012: true
            bytecart.BC7013: true
            bytecart.BC7014: true
            bytecart.BC7020: true
            bytecart.BC7021: true
            bytecart.BC8010: true
            bytecart.BC8020: true
            bytecart.BC9000: true
            bytecart.BC9001: true
            bytecart.BC9002: true
            bytecart.BC9004: true
            bytecart.BC9008: true
            bytecart.BC9016: true
            bytecart.bcupdater: true

    bytecart.helper:
        description: give acces to small subnets and station blocks
        children:
            bytecart.BC7001: true
            bytecart.BC7002: true
            bytecart.BC7003: true
            bytecart.BC7010: true
            bytecart.BC7011: false
            bytecart.BC7012: true
            bytecart.BC7013: true
            bytecart.BC7014: true
            bytecart.BC7020: true
            bytecart.BC7021: true
            bytecart.BC8010: false
            bytecart.BC8020: false
            bytecart.BC9000: true
            bytecart.BC9001: true
            bytecart.BC9002: true
            bytecart.BC9004: true
            bytecart.BC9008: false
            bytecart.BC9016: false

    bytecart.subnetwork:
        description: give acces to all subnets and station blocks
        children:
            bytecart.BC7001: true
            bytecart.BC7002: true
            bytecart.BC7003: true
            bytecart.BC7010: true
            bytecart.BC7011: false
            bytecart.BC7012: true
            bytecart.BC7013: true
            bytecart.BC7014: true
            bytecart.BC7020: true
            bytecart.BC7021: true
            bytecart.BC8010: false
            bytecart.BC8020: false
            bytecart.BC9000: true
            bytecart.BC9001: true
            bytecart.BC9002: true
            bytecart.BC9004: true
            bytecart.BC9008: true
            bytecart.BC9016: true
    bytecart.BC7001:
        default: true
    bytecart.BC7002:
        default: true
    bytecart.BC7003:
        default: true
    bytecart.BC7010:
        default: true
    bytecart.BC7011:
        default: false
    bytecart.BC7012:
        default: true
    bytecart.BC7013:
        default: true
    bytecart.BC7014:
        default: true
    bytecart.BC7020:
        default: true
    bytecart.BC7021:
        default: true
    bytecart.BC8010:
        default: false
    bytecart.BC8020:
        default: false
    bytecart.BC9000:
        default: false
    bytecart.BC9001:
        default: false
    bytecart.BC9002:
        default: false
    bytecart.BC9004:
        default: false
    bytecart.BC9008:
        default: false
    bytecart.BC9016:
        default: false
    bytecart.mego:
        default: true
    bytecart.sendto:
        default: true
    bytecart.bcupdater:
        default: false

commands:
    mego:
        description: set ByteCart destination address in your inventory
        usage: "Usage : /<command> address [train], where address is formatted as a.b.c"
        permission: bytecart.mego
        permission-message: You don't have permission <permission>
        
    sendto:
        description: set ByteCart destination address in a storage cart inventory
        usage: "Usage : /<command> address [train], where address is formatted as a.b.c"
        permission: bytecart.sendto
        permission-message: You don't have permission <permission>

    bcupdater:
        description: set a cart as Updater for ByteCart
        usage: "Usage : /<command>"
        permission: bytecart.bcupdater
        permission-message: You don't have permission <permission>