name: ByteCart
main: com.github.catageek.ByteCart.ByteCart
version: 0.7
permissions:
    bytecart.*:
        description: give access to all blocks
        children:
            bytecart.BC7001: true
            bytecart.BC7002: true
            bytecart.BC7003: true
            bytecart.BC7010: true
            bytecart.BC7011: true
            bytecart.BC8010: true
            bytecart.BC8020: true
            bytecart.BC9000: true
            bytecart.BC9001: true
            bytecart.BC9002: true
            bytecart.BC9004: true
            bytecart.BC9008: true
            bytecart.BC9016: true

    bytecart.helper:
        description: give acces to small subnets and station blocks
        children:
            bytecart.BC7001: true
            bytecart.BC7002: true
            bytecart.BC7003: true
            bytecart.BC7010: true
            bytecart.BC7011: false
            bytecart.BC8010: false
            bytecart.BC8020: false
            bytecart.BC9000: true
            bytecart.BC9001: true
            bytecart.BC9002: true
            bytecart.BC9004: true
            bytecart.BC9008: false
            bytecart.BC9016: false

    bytecart.subnetwork:
        description: give acces to all subnets and station blocks
        children:
            bytecart.BC7001: true
            bytecart.BC7002: true
            bytecart.BC7003: true
            bytecart.BC7010: true
            bytecart.BC7011: false
            bytecart.BC8010: false
            bytecart.BC8020: false
            bytecart.BC9000: true
            bytecart.BC9001: true
            bytecart.BC9002: true
            bytecart.BC9004: true
            bytecart.BC9008: true
            bytecart.BC9016: true
    bytecart.BC7001:
        default: true
    bytecart.BC7002:
        default: true
    bytecart.BC7003:
        default: true
    bytecart.BC7010:
        default: true
    bytecart.BC7011:
        default: false
    bytecart.BC8010:
        default: false
    bytecart.BC8020:
        default: false
    bytecart.BC9000:
        default: false
    bytecart.BC9001:
        default: false
    bytecart.BC9002:
        default: false
    bytecart.BC9004:
        default: false
    bytecart.BC9008:
        default: false
    bytecart.BC9016:
        default: false
